routes/web.php
<?php
use App\Book;
use App\vehicle;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('books', 'BookController');

Route::get('/', 'BookController@index');

app/Book.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Book extends Eloquent
{
    //

    protected $mappingProperties = [
        'id' => [
                'type' => 'string',
                'analyzer' => 'standard'
        ],
        'isbn' => [
                'type' => 'string',
                'analyzer' => 'standard'
        ],
        'title' => [
                'type' => 'string',
                'analyzer' => 'standard'
        ],
        'author' => [
                'type' => 'string',
                'analyzer' => 'standard'
        ],
        'category' => [
                'type' => 'string',
                'analyzer' => 'standard'
        ],
    ];

    public function getIndexDocumentData()
    {
        return array(
            'id'        => $this->id,
            'isbn'      => $this->isbn,
            'title'     => $this->title,
            'author'    => $this->author,
            'category'  => $this->category
        );
    }

    public function getTypeName()
    {
        return 'books';
    }

    
    /*
    //this function to solve this error:
    Elasticsearch\Common\Exceptions\BadRequest400Exception with message 'illegal_argument_exception: 
    The parameter [fields] is no longer supported, please use [stored_fields] to retrieve stored fields 
    or _source filtering if the field is not stored'
    */
    private function buildFieldsParameter($getSourceIfPossible, $getTimestampIfPossible) { 
        return null; 
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Book;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Collection;
use App\Transformer\BookTransformer;
use League\Fractal\Resource\Item as Item;
use Leaque\Fractal;

use League\Fractal\Manager;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::all();
        $books_mysql = \DB::connection('mysql2')->table('books')->get();

        return view('elasticquent.bookindex', compact('books','books_mysql'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.bookadd');
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        function storeMysql($request){

            \DB::connection('mysql2')->table('books')->insert(
                ['title' => $request->input('title'),
                 'isbn' => $request->input('isbn'),
                 'author' => $request->input('author'),
                 'category' => $request->input('category'),
                ]
            );
        }

        function storeMongodb($request){

            $book = new Book;
            $book->title =  $request->input('title');
            $book->isbn =  $request->input('isbn');
            $book->author =  $request->input('author');
            $book->category = $request->input('category') ;
            $book->save();

        }

        $dbtype = $request->input('dbtype');

        if($dbtype == 'Both'){
            storeMysql($request);
            storeMongodb($request);

        } else if ($dbtype == 'MySql'){
            storeMysql($request);

        } else if ($dbtype == 'MongoDB'){
            storeMongodb($request);
        }

        return redirect()->route('books.index')->withErrors(['msg' => 'New book added !']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $book = Book::find($id);
      return fractal()->item($book, new BookTransformer);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $book = Book::find($id);
      return view('books.bookedit', compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $book = Book::find($id);
      $book->title = $request->input('title');
      $book->isbn = $request->input('isbn');
      $book->author = $request->input('author');
      $book->category = $request->input('category');
      $book->save();
      $books = Book::all();
      return fractal()->collection($books)->transformWith(new BookTransformer())->includeCharacters()->toArray();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $book = Book::find($id);
      $book->delete();
      $books = Book::all();
      return fractal()->collection($books)->transformWith(new BookTransformer())->includeCharacters()->toArray();
    }
}

resources/views/books/bookadd.blade.php
<!DOCTYPE html>
<html>
<head><title>Book Index</title>
<link href="/css/lib.css" rel="stylesheet">
</head>
<body>
<h2>Add Book</h2>

<hr/>

<form action="{{ route('books.store') }}" method="post">

{{ csrf_field() }}

  <label for="title">Title</label>
  <input type="text" name="title" value="">
  <br/><br/>
  <label for="isbn">ISBN</label>
  <input type="text" name="isbn" value="">
  <br/><br/>
  <label for="author">Author</label>
  <input type="text" name="author" value="">
  <br/><br/>
  <label for="category">Category</label>
  <input type="text" name="category" value="">
  <br/><br/>
  <label for="category">DB</label>
  <select name="dbtype">
    <option> Both </option>
    <option> MySql </option>
    <option> MongoDB </option>
  </select>
  <br/><hr/><br />

  <input type="button" class="book-action big" value="Cancel" onclick="window.location='{{ route('books.index') }}'">
  <input type="reset" class="book-action big">
  <input type="submit" class="book-action big" value="Submit">

</form>


</body>
</html>

resources/views/books/bookedit.blade.php
<!DOCTYPE html>
<html>
<head><title>Edit Book</title>
<link href="/css/lib.css" rel="stylesheet">
</head>
<body>
<h1>Welcome to Library (MongoDB)</h1>
<h2>Edit Book</h2>

<hr/>

<form action="{{ route('books.update',['id' =>  $book{'_id'} ]) }}" method="post">
{{ csrf_field() }}
<label for="title">Title</label><input type="text" name="title" value="{{ $book{'title'} }}">
<label for="isbn">ISBN</label><input type="text" name="isbn" value="{{ isset( $book{'isbn'} ) ?  $book{'isbn'} : ' - ' }}">
<label for="author">Author</label><input type="text" name="author" value="{{ $book{'author'} }}">
<label for="category">Category</label><input type="text" name="category" value="{{ $book{'category'} }}">
<br/><hr/>

  <input type="button" class="book-action big" value="Cancel" onclick="window.location='{{ route('books.index') }}'"/>
  <input type="reset" class="book-action big" />
  <input type="hidden" name="_method" value="PUT"/>
  <input type="submit" class="book-action big" name="sub" value="Submit"/>

</form>



</body>
</html>

resources/views/books/bookindex.blade.php
<!DOCTYPE html>
<html>
<head>
<title>Book Index</title>
<link href="/css/lib.css" rel="stylesheet">
</head>
<body>
<h1>Welcome to Library (MongoDB)</h1>
<h2>Index of Books</h2>
<table>

<th>No</th><th>Book Title</th><th>ISBN</th><th>Author</th><th>Category</th><th>Action</th>
<tbody>
@foreach ($books as $i => $book)
		<tr>
			<td>{{ $i+1 }}</td>
			<td>{{ $book{'title'} }}</td>
			<td>{{ isset( $book{'isbn'} ) ?  $book{'isbn'} : ' - ' }}</td>
 			<td>{{ $book{'author'} }}</td>
 			<td>{{ $book{'category'} }}</td>
 			<td><form action="books/{{ $book{'_id'} }}" method="POST">
 				{{ csrf_field() }}
 				<input type="button" class="book-action" value="View" onclick="window.location='{{ route('books.show', ['book' => $book{'_id'}]) }}'"> &nbsp;
 				<input type="button" class="book-action" value="Edit" onclick="window.location='{{ route('books.edit', ['book' => $book{'_id'}]) }}'"> &nbsp;
				<input type="hidden" class="book-action" name="_method" value="DELETE"/>
				<input type="submit" class="book-action" name="del" value="Delete"/>
				</form>
			</td>

		</tr>
@endforeach
</tbody>
</table>
<hr/>

<input type="button" class="book-action big" value="Add a Book" onclick="window.location='{{ route('books.create') }}'">
</body>
</html>

resources/views/books/bookview.blade.php
<!DOCTYPE html>
<html>
<head>
<title>View Book</title>
<link href="/css/lib.css" rel="stylesheet">
</head>
<body>
<h1>{{ $book{'title'} }} </h1>
<p>{{ $book{'category'} }}</p>

<br/><hr/>

  <input type="button" class="book-action big" value="Return" onclick="window.location='{{ route('books.index') }}'">
</body>
</html>